name: release
on:
  release:
    types:
      - created

jobs:
  publish:
    runs-on: ubuntu-22.04
    steps:
      - name: Pull code
        uses: actions/checkout@v3
      - name: Set up Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x
      - name: Build
        run: deno run --allow-all build.ts
      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: https://registry.npmjs.org
      - name: Publish to npm
        run: npm publish npm/
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
